export const SAVE_SETTINGS = 'SAVE_SETTINGS';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GO_TO_NEXT_MONTH = 'GO_TO_NEXT_MONTH';
export const GO_TO_PREVIOUS_MONTH = 'GO_TO_PREVIOUS_MONTH';
export const SAVE_MONTH = 'SAVE_MONTH';
export const REMOVE_MONTH = 'REMOVE_MONTH';
