export const SAVE_SETTINGS = 'SAVE_SETTINGS';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GO_TO_DATE = 'GO_TO_DATE';
export const SAVE_DATE = 'SAVE_DATE';
export const REMOVE_DATES = 'REMOVE_DATES';
export const REMOVE_DATES_BEFORE_START = 'REMOVE_DATES_BEFORE_START';
